import type { Language } from "./types";

export const copy = {
  zh: {
    subtitle: "链上行为变化调查智能体",
    network: "Ethereum 主网",
    heroTitle: "发现地址异常，溯源动因，评估风险影响",
    heroDescription: "ChainScope AI 对比地址历史基准行为，识别资金异动，解析 ETH、ERC-20、内部交易与多跳关联，定位异常根源并评估潜在风险。",
    placeholder: "输入 Ethereum 地址：0x...",
    start: "开始调查",
    investigating: "调查中...",
    initialStatus: "",
    overview: "变化分析",
    trace: "Agent 追踪",
    report: "AI 报告",
    evidence: "原始证据",
    rootRisk: "根地址风险",
    observedEvents: "观测事件",
    changeSignals: "明显变化",
    agentTrace: "Agent 追踪",
    whatChanged: "发生了什么变化",
    whatChangedDesc: "程序对比近期行为与前一个基准窗口，找出真正发生变化的指标。",
    whyChanged: "为什么可能发生变化",
    whyChangedDesc: "基于已观测链上证据形成多个原因假设，而不是直接猜测唯一原因。",
    potentialImpact: "潜在影响",
    potentialImpactDesc: "分析当前变化如果持续，可能对资金、关系网络和后续调查造成什么影响。",
    supportingEvidence: "支撑证据",
    supportingEvidenceDesc: "异常、对手方和第二跳用于支撑变化解释，而不是作为最终结论。",
    recent: "近期",
    baseline: "基准",
    confidence: "置信度",
    high: "高",
    medium: "中",
    low: "低",
    noChange: "当前样本中没有检测到明显行为变化。",
    noCause: "当前证据不足以形成明确原因假设。",
    noImpact: "当前没有检测到显著潜在影响。",
    traceTitle: "Agent 调查路径",
    traceDesc: "当程序发现值得继续验证的关系时，Agent 会自动选择一个直接对手方继续调查。",
    rootWallet: "根地址",
    directRelation: "直接链上关系",
    firstHop: "第一跳调查目标",
    continueInvestigation: "Agent 继续调查",
    secondHop: "第二跳关系",
    secondHopDesc: "这些地址主要与第一跳地址交互，不一定直接与根地址有关。",
    important: "重要说明",
    importantText: "第二跳行为不会直接加入根地址 Risk Score。链上关系也不等于共同身份、共同控制或恶意行为。",
    reportTitle: "AI 变化调查报告",
    reportDesc: "DeepSeek 只负责解释程序计算出的变化、原因假设、潜在影响和真实链上证据。",
    evidenceTitle: "原始证据",
    evidenceDesc: "与异常规则直接关联的交易会自动标记为重点证据，其余记录仍可用于人工核查。",
    anomalies: "异常信号",
    ethTransactions: "ETH 普通交易",
    tokenTransfers: "ERC-20 转账",
    internalTransactions: "Internal Transactions",
    noSecondHop: "当前没有找到适合继续自动追踪的直接对手方。",
    generating: "正在生成变化调查报告...",
    evidenceReason: "该交易被至少一个异常检测规则引用。",
  },
  en: {
    subtitle: "On-chain Behavior Change Investigation Agent",
    network: "Ethereum Mainnet",
    heroTitle: "Detect address anomalies, trace root causes, assess risk impact",
    heroDescription: "ChainScope AI compares an address against its historical baseline behavior, detects fund anomalies, and parses ETH, ERC-20, internal transactions and multi-hop relationships to locate the root cause and assess potential risk.",
    placeholder: "Enter Ethereum address: 0x...",
    start: "Start Investigation",
    investigating: "Investigating...",
    initialStatus: "",
    overview: "Change Analysis",
    trace: "Agent Trace",
    report: "AI Report",
    evidence: "Evidence",
    rootRisk: "Root Risk",
    observedEvents: "Observed Events",
    changeSignals: "Major Changes",
    agentTrace: "Agent Trace",
    whatChanged: "What Changed",
    whatChangedDesc: "The program compares recent behavior with the previous baseline window to identify meaningful changes.",
    whyChanged: "Why It May Have Changed",
    whyChangedDesc: "Possible causes are formed from observed on-chain evidence instead of assuming a single explanation.",
    potentialImpact: "Potential Impact",
    potentialImpactDesc: "What the observed change may affect if the behavior continues.",
    supportingEvidence: "Supporting Evidence",
    supportingEvidenceDesc: "Anomalies, counterparties and second-hop relationships support the explanation rather than acting as the conclusion.",
    recent: "Recent",
    baseline: "Baseline",
    confidence: "Confidence",
    high: "High",
    medium: "Medium",
    low: "Low",
    noChange: "No major behavioral change was detected in the current sample.",
    noCause: "Current evidence is insufficient to form a strong cause hypothesis.",
    noImpact: "No significant potential impact was detected.",
    traceTitle: "Agent Investigation Path",
    traceDesc: "When a relationship is worth validating, the agent automatically selects one direct counterparty for deeper investigation.",
    rootWallet: "Root Wallet",
    directRelation: "Direct on-chain relationship",
    firstHop: "First-Hop Investigation Target",
    continueInvestigation: "Agent continues investigation",
    secondHop: "Second-Hop Relationships",
    secondHopDesc: "These addresses mainly interact with the selected first-hop address and are not necessarily directly related to the root wallet.",
    important: "Important",
    importantText: "Second-hop behavior does not directly affect the root Risk Score. An on-chain relationship does not prove shared identity, control, ownership or malicious intent.",
    reportTitle: "AI Change Investigation Report",
    reportDesc: "DeepSeek only explains deterministic changes, cause hypotheses, potential impacts and real blockchain evidence supplied by ChainScope.",
    evidenceTitle: "Raw Evidence",
    evidenceDesc: "Transactions directly referenced by anomaly rules are automatically highlighted while the remaining records stay available for verification.",
    anomalies: "Anomaly Signals",
    ethTransactions: "ETH Transactions",
    tokenTransfers: "ERC-20 Transfers",
    internalTransactions: "Internal Transactions",
    noSecondHop: "No suitable direct counterparty was selected for deeper tracing.",
    generating: "Generating change investigation report...",
    evidenceReason: "This transaction is referenced by at least one anomaly detection rule.",
  },
} as const;

export function getCopy(language: Language) {
  return copy[language];
}
